# 
# MMU "Happy Hare edition" menus
#
[include mmu_klipperscreen.conf]

# 
# ERCF "Happy Hare edition" menus
#
[include ercf_klipperscreen.conf]

[main]
# Invert axis in move panel. Default is False. Change to true to invert
invert_x: False
invert_y: False
invert_z: False
# Time (seconds) before the Job Status page reverts to main menu after a successful job
# job_complete_timeout: 30
# Time (seconds) before the Job Status page reverts to main menu after a successful job.
#   If this option is 0, the user must click on a button to go back to the main menu.
job_error_timeout: 0
# Specify the language
# The language can be specified here instead of using the system default language.
language: en
# Allows the cursor to be displayed on the screen
show_cursor: False

[printer Voron V2.4784]
# Define the moonraker host/port if different from 127.0.0.1 and 7125
moonraker_host: 127.0.0.1
moonraker_port: 7125
# Moonraker API key if this is not connecting from a trusted client IP
moonraker_api_key: 772d7f1f5233497b8ba21ab6a94fa8e6
# Define the z_babystep intervals in a CSV list. Currently only 2 are supported
z_babystep_values: 0.1, 0.05
# camera_url: http://127.0.0.1/webcam/?action=stream

[preheat PLA]
extruder: 220
heater_bed: 60
[preheat ABS]
extruder: 250
heater_bed: 105

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# print_estimate_method = slicer
#~# 24htime = False
#~# font_size = small
#~# confirm_estop = True
#~# use_dpms = False
#~# show_heater_power = True
#~# move_speed_xy = 100
#~# move_speed_z = 20
#~# print_sort_dir = date_desc
#~# language = en
#~# 
#~# [displayed_macros Voron V2.660]
#~# adaptive_purge = False
#~# animate = False
#~# bed_mesh_calibrate = False
#~# attach_probe_lock = False
#~# cancel_print = False
#~# dock_probe_unlock = False
#~# filament_abs = False
#~# filament_other = False
#~# filament_asa = False
#~# filament_petg = False
#~# get_timelapse_setup = False
#~# dump_warnings = False
#~# exhaust_time = False
#~# hyperlapse = False
#~# filament_tpu = False
#~# filament_pla = False
#~# extrusion_test = False
#~# filament_runout = False
#~# g32 = False
#~# heater_test = False
#~# m300 = False
#~# probe_accuracy = False
#~# probe_calibrate = False
#~# m600 = False
#~# print_start = False
#~# pa_cal = False
#~# set_logo_leds_off = False
#~# set_nozzle_leds_off = False
#~# set_nozzle_leds_on = False
#~# set_underglow_leds_off = False
#~# set_underglow_leds_on = False
#~# print_end = False
#~# status_busy = False
#~# status_calibrating_z = False
#~# set_caselight_full = False
#~# status_cleaning = False
#~# test_stream_delay = False
#~# set_caselight_off = False
#~# timelapse_render = False
#~# status_heating = False
#~# status_maintenance = False
#~# timelapse_take_frame = False
#~# status_paused = False
#~# status_homing = False
#~# status_meshing = False
#~# status_leveling = False
#~# status_printing = False
#~# set_caselight_on = False
#~# status_off = False
#~# resume = False
#~# pause = False
#~# search_vars = False
#~# status_ready = False
#~# start_temp_monitor = False
#~# set_pa = False
#~# stop_temp_monitor = False
#~# toggle_caselight = False
#~# start_equery = False
#~# test_speed = False
#~# stop_equery = False
#~# 
#~# [graph Voron V2.660]
#~# heater_bed = False
#~# 
#~# [graph Voron V2.4784]
#~# temperature_sensor chamber_temp = False
#~# temperature_sensor raspberry_pi = False
#~# heater_bed = False
#~#
